In [39]:
import pandas as pd
df = pd.read_csv("mrw_1992_appendix.csv")
df.head()

,No,Country,Non_oil,Intermediate,OECD,GDP_1960,GDP_1985,GDP_growth_pct,Working_age_growth_pct,Investment_pct_GDP,School_pct
0,1,Algeria,1,1,0,2485.0,4371.0,4.8,2.6,24.1,4.5
1,2,Angola,1,0,0,1588.0,1171.0,0.8,2.1,5.8,1.8
2,3,Benin,1,0,0,1116.0,1071.0,2.2,2.4,10.8,1.8
3,4,Botswana,1,1,0,959.0,3671.0,8.6,3.2,28.3,2.9
4,5,Burkina Faso,1,0,0,529.0,857.0,2.9,0.9,12.7,0.4

In [40]:
print(df.shape)
print(df.columns.tolist())

(121, 11)
['No', 'Country', 'Non_oil', 'Intermediate', 'OECD', 'GDP_1960', 'GDP_1985', 'GDP_growth_pct', 'Working_age_growth_pct', 'Investment_pct_GDP', 'School_pct']

In [42]:
non_oil = df[df["Non_oil"] == 1].copy()
intermediate = df[df["Intermediate"] == 1].copy()
oecd = df[df["OECD"] == 1].copy()

print("Non-oil sample:",len(non_oil))
print("Intermediate sample:", len(intermediate))
print("OECD sample:", len(oecd))

Non-oil sample: 98
Intermediate sample: 75
OECD sample: 22

In [43]:
import numpy as np
df["ln_GDP_1985"] = np.log(df["GDP_1985"])
df["ln_investment"] = np.log(df["Investment_pct_GDP"]/100)
df["ln_ngd"] = np.log(df["Working_age_growth_pct"]/100 + 0.05)

In [44]:
df[["Country", "ln_GDP_1985", "ln_investment", "ln_ngd"]].head()

        Country  ln_GDP_1985  ln_investment    ln_ngd
0       Algeria     8.382747      -1.422958 -2.577022
1        Angola     7.065613      -2.847312 -2.645075
2         Benin     6.976348      -2.225624 -2.603690
3      Botswana     8.208219      -1.262308 -2.501036
4  Burkina Faso     6.753438      -2.063568 -2.830218

In [45]:
non_oil = df[df["Non_oil"] == 1].copy()
intermediate = df[df["Intermediate"] == 1].copy()
oecd = df[df["OECD"] == 1].copy()

print("Non-oil:", len(non_oil))
print("Intermediate:", len(intermediate))
print("OECD", len(oecd))

Non-oil: 98
Intermediate: 75
OECD 22

In [46]:
df["ln_school"] = np.log(df["School_pct"]/100)
df[["Country", "ln_school"]].head()

        Country  ln_school
0       Algeria  -3.101093
1        Angola  -4.017384
2         Benin  -4.017384
3      Botswana  -3.540459
4  Burkina Faso  -5.521461

In [47]:
df[["Country", "ln_GDP_1985", "ln_investment", "ln_ngd", "ln_school"]].head()

        Country  ln_GDP_1985  ln_investment    ln_ngd  ln_school
0       Algeria     8.382747      -1.422958 -2.577022  -3.101093
1        Angola     7.065613      -2.847312 -2.645075  -4.017384
2         Benin     6.976348      -2.225624 -2.603690  -4.017384
3      Botswana     8.208219      -1.262308 -2.501036  -3.540459
4  Burkina Faso     6.753438      -2.063568 -2.830218  -5.521461

In [48]:

# UM of non oil
import statsmodels.api as sm
non_oil = df[df["Non_oil"] == 1].copy()
y = non_oil["ln_GDP_1985"]
X = non_oil[["ln_investment", "ln_ngd"]]
X = sm.add_constant(X)
model = sm.OLS(y,X).fit()
print(model.summary())

# RM of non oil
non_oil["restricted_x"] = (non_oil["ln_investment"] - non_oil["ln_ngd"])
non_oil[["Country", "restricted_x"]].head()
y_r = non_oil["ln_GDP_1985"]
X_r = non_oil[["restricted_x"]]
X_r = sm.add_constant(X_r)
model_r = sm.OLS(y_r, X_r).fit()
print(model_r.summary())

# F test
f_test = model.f_test("ln_investment + ln_ngd = 0")
print(f_test)
print("F-statistic:", float(f_test.fvalue))
print("P-value:", float(f_test.pvalue))

# alpha and se
b1 = model_r.params["restricted_x"]
alpha = b1 / (1+b1)
print("Estimated coefficient:", b1)

se_b1 = model_r.bse["restricted_x"]
se_alpha = se_b1 / (1+b1)**2
print("Implied alpha:", round(alpha, 4))
print("Standard error of alpha:", round(se_alpha, 4))

                            OLS Regression Results
==============================================================================
Dep. Variable:            ln_GDP_1985   R-squared:                       0.601
Model:                            OLS   Adj. R-squared:                  0.592
Method:                 Least Squares   F-statistic:                     71.51
Date:                Thu, 29 Oct 2026   Prob (F-statistic):           1.13e-19
Time:                        23:15:34   Log-Likelihood:                -101.04
No. Observations:                  98   AIC:                             208.1
Df Residuals:                      95   BIC:                             215.8
Df Model:                           2
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             5.4299      1.584      3.428      0.001       2.285       8.574
ln_investment     1.4240      0.143      9.951      0.000       1.140       1.708
ln_ngd           -1.9898      0.563     -3.532      0.001      -3.108      -0.871
==============================================================================
Omnibus:                        2.881   Durbin-Watson:                   1.453
Prob(Omnibus):                  0.237   Jarque-Bera (JB):                2.631
Skew:                          -0.401   Prob(JB):                        0.268
Kurtosis:                       2.976   Cond. No.                         81.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:            ln_GDP_1985   R-squared:                       0.597
Model:                            OLS   Adj. R-squared:                  0.593
Method:                 Least Squares   F-statistic:                     142.4
Date:                Thu, 29 Oct 2026   Prob (F-statistic):           1.13e-20
Time:                        23:15:34   Log-Likelihood:                -101.46
No. Observations:                  98   AIC:                             206.9
Df Residuals:                      96   BIC:                             212.1
Df Model:                           1
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            6.8724      0.121     56.995      0.000       6.633       7.112
restricted_x     1.4880      0.125     11.934      0.000       1.241       1.735
==============================================================================
Omnibus:                        4.010   Durbin-Watson:                   1.421
Prob(Omnibus):                  0.135   Jarque-Bera (JB):                3.720
Skew:                          -0.477   Prob(JB):                        0.156
Kurtosis:                       3.015   Cond. No.                         3.15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
<F test: F=0.8342623015828147, p=0.3633551936926596, df_denom=95, df_num=1>
F-statistic: 0.8342623015828147
P-value: 0.3633551936926596
Estimated coefficient: 1.4879939859711748
Implied alpha: 0.5981
Standard error of alpha: 0.0201

In [49]:
# UM of intermediate
intermediate = df[df["Intermediate"] == 1].copy()
y_int = intermediate["ln_GDP_1985"]
X_int = intermediate[["ln_investment", "ln_ngd"]]
X_int = sm.add_constant(X_int)
model_int = sm.OLS(y_int,X_int).fit()
print(model_int.summary())

# RM of intermediated
intermediate["restricted_x"] = (intermediate["ln_investment"] - intermediate["ln_ngd"])
intermediate[["Country", "restricted_x"]].head()
y_int_r = intermediate["ln_GDP_1985"]
X_int_r = intermediate[["restricted_x"]]
X_int_r = sm.add_constant(X_int_r)
model_int_r = sm.OLS(y_int_r, X_int_r).fit()
print(model_int_r.summary())

# F test
f_test_int = model_int.f_test("ln_investment + ln_ngd = 0")
print(f_test_int)
print("F-statistic:", float(f_test_int.fvalue))
print("P-value:", float(f_test_int.pvalue))

# alpha and se
b1_int = model_int_r.params["restricted_x"]
alpha_int = b1_int / (1+b1_int)
print("Estimated coefficient:", b1_int)

se_b1_int = model_int_r.bse["restricted_x"]
se_alpha_int = se_b1_int / (1+b1_int)**2
print("Implied alpha_int:", round(alpha_int, 4))
print("Standard error of alpha_int:", round(se_alpha_int, 4))

                            OLS Regression Results
==============================================================================
Dep. Variable:            ln_GDP_1985   R-squared:                       0.599
Model:                            OLS   Adj. R-squared:                  0.588
Method:                 Least Squares   F-statistic:                     53.76
Date:                Thu, 29 Oct 2026   Prob (F-statistic):           5.21e-15
Time:                        23:15:44   Log-Likelihood:                -67.896
No. Observations:                  75   AIC:                             141.8
Df Residuals:                      72   BIC:                             148.7
Df Model:                           2
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             5.3459      1.543      3.464      0.001       2.270       8.422
ln_investment     1.3176      0.171      7.708      0.000       0.977       1.658
ln_ngd           -2.0172      0.534     -3.778      0.000      -3.081      -0.953
==============================================================================
Omnibus:                        6.292   Durbin-Watson:                   1.993
Prob(Omnibus):                  0.043   Jarque-Bera (JB):                5.650
Skew:                          -0.537   Prob(JB):                       0.0593
Kurtosis:                       3.808   Cond. No.                         76.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:            ln_GDP_1985   R-squared:                       0.592
Model:                            OLS   Adj. R-squared:                  0.586
Method:                 Least Squares   F-statistic:                     105.8
Date:                Thu, 29 Oct 2026   Prob (F-statistic):           7.58e-16
Time:                        23:15:44   Log-Likelihood:                -68.564
No. Observations:                  75   AIC:                             141.1
Df Residuals:                      73   BIC:                             145.8
Df Model:                           1
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            7.0929      0.146     48.711      0.000       6.803       7.383
restricted_x     1.4310      0.139     10.286      0.000       1.154       1.708
==============================================================================
Omnibus:                        8.966   Durbin-Watson:                   1.926
Prob(Omnibus):                  0.011   Jarque-Bera (JB):                8.912
Skew:                          -0.672   Prob(JB):                       0.0116
Kurtosis:                       4.023   Cond. No.                         3.87
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
<F test: F=1.2933271592877071, p=0.25920630472728245, df_denom=72, df_num=1>
F-statistic: 1.2933271592877071
P-value: 0.25920630472728245
Estimated coefficient: 1.430955376328648
Implied alpha_int: 0.5886
Standard error of alpha_int: 0.0235

In [50]:
# UM of oecd
oecd = df[df["OECD"] == 1].copy()
y_oecd = oecd["ln_GDP_1985"]
X_oecd = oecd[["ln_investment", "ln_ngd"]]
X_oecd = sm.add_constant(X_oecd)
model_oecd = sm.OLS(y_oecd,X_oecd).fit()
print(model_oecd.summary())

#RM of oecd
oecd["restricted_x"] = (oecd["ln_investment"] - oecd["ln_ngd"])
oecd[["Country", "restricted_x"]].head()
y_oecd_r = oecd["ln_GDP_1985"]
X_oecd_r = oecd[["restricted_x"]]
X_oecd_r = sm.add_constant(X_oecd_r)
model_oecd_r = sm.OLS(y_oecd_r, X_oecd_r).fit()
print(model_oecd_r.summary())

# F test
f_test_oecd = model_oecd.f_test("ln_investment + ln_ngd = 0")
print(f_test_oecd)
print("F-statistic:", float(f_test_oecd.fvalue))
print("P-value:", float(f_test_oecd.pvalue))

# alpha and se
b1_oecd = model_oecd_r.params["restricted_x"]
alpha_oecd = b1_oecd / (1+b1_oecd)
print("Estimated coefficient:", b1_oecd)
se_b1_oecd = model_oecd_r.bse["restricted_x"]
se_alpha_oecd = se_b1_oecd / (1+b1_oecd)**2
print("Implied alpha_oecd:", round(alpha_oecd, 4))
print("Standard error of alpha_oecd:", round(se_alpha_oecd, 4))

                            OLS Regression Results
==============================================================================
Dep. Variable:            ln_GDP_1985   R-squared:                       0.106
Model:                            OLS   Adj. R-squared:                  0.012
Method:                 Least Squares   F-statistic:                     1.126
Date:                Thu, 29 Oct 2026   Prob (F-statistic):              0.345
Time:                        23:15:49   Log-Likelihood:                -8.1659
No. Observations:                  22   AIC:                             22.33
Df Residuals:                      19   BIC:                             25.60
Df Model:                           2
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             8.0206      2.518      3.185      0.005       2.751      13.291
ln_investment     0.4999      0.434      1.152      0.264      -0.408       1.408
ln_ngd           -0.7419      0.852     -0.871      0.395      -2.526       1.042
==============================================================================
Omnibus:                        4.010   Durbin-Watson:                   1.796
Prob(Omnibus):                  0.135   Jarque-Bera (JB):                2.575
Skew:                          -0.829   Prob(JB):                        0.276
Kurtosis:                       3.239   Cond. No.                         109.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:            ln_GDP_1985   R-squared:                       0.103
Model:                            OLS   Adj. R-squared:                  0.058
Method:                 Least Squares   F-statistic:                     2.299
Date:                Thu, 29 Oct 2026   Prob (F-statistic):              0.145
Time:                        23:15:49   Log-Likelihood:                -8.2007
No. Observations:                  22   AIC:                             20.40
Df Residuals:                      20   BIC:                             22.58
Df Model:                           1
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            8.6244      0.533     16.172      0.000       7.512       9.737
restricted_x     0.5538      0.365      1.516      0.145      -0.208       1.316
==============================================================================
Omnibus:                        4.283   Durbin-Watson:                   1.855
Prob(Omnibus):                  0.117   Jarque-Bera (JB):                2.818
Skew:                          -0.869   Prob(JB):                        0.244
Kurtosis:                       3.236   Cond. No.                         14.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
<F test: F=0.060341244390892265, p=0.8085913104928671, df_denom=19, df_num=1>
F-statistic: 0.060341244390892265
P-value: 0.8085913104928671
Estimated coefficient: 0.5538445177862308
Implied alpha_oecd: 0.3564
Standard error of alpha_oecd: 0.1513

In [58]:
# Augumented Solow Model 
# UM of non oil
non_oil = df[df["Non_oil"] == 1].copy()
y_Au = non_oil["ln_GDP_1985"]
X_Au = non_oil[["ln_investment", "ln_ngd", "ln_school"]]
X_Au = sm.add_constant(X_Au)
model_Au = sm.OLS(y_Au,X_Au).fit()
print(model_Au.summary())

# RM of non oil
non_oil["restricted_k"] = (non_oil["ln_investment"] - non_oil["ln_ngd"])
non_oil["restricted_h"] = (non_oil["ln_school"] - non_oil["ln_ngd"])

y_Au_r = non_oil["ln_GDP_1985"]
X_Au_r = non_oil[["restricted_k", "restricted_h"]]
X_Au_r = sm.add_constant(X_Au_r)
model_Au_r = sm.OLS(y_Au_r, X_Au_r).fit()
print(model_Au_r.summary())

# F test
f_test = model_Au.f_test("ln_investment + ln_ngd + ln_school = 0")
print(f_test)
print("F-statistic:", float(f_test.fvalue))
print("P-value:", float(f_test.pvalue))

# alpha and beta
b1 = model_Au_r.params["restricted_k"]
b2 = model_Au_r.params["restricted_h"]

alpha = b1 / (1+b1+b2)
beta = b2 / (1+b1+b2)

print("physical capital coefficient:", b1)
print("human capital coefficient:", b2)
print("Implied alpha:", round(alpha, 4))
print("Implied beta:", round(beta, 4))

# se of alpha and beta
cov_matrix = model_Au_r.cov_params().loc[["restricted_k", "restricted_h"], ["restricted_k", "restricted_h"]].to_numpy()
grad_alpha = np.array([(1 + b2) / (1+b1+b2)**2, -b1 / (1+b1+b2)**2])
grad_beta = np.array([-b2 / (1+b1+b2)**2,(1 + b1) / (1+b1+b2)**2])
se_alpha = np.sqrt(grad_alpha @ cov_matrix @ grad_alpha)
se_beta = np.sqrt(grad_beta @ cov_matrix @ grad_beta)

print("se of alpha:", round(se_alpha, 4))
print("se of beta:", round(se_beta, 4))

                            OLS Regression Results
==============================================================================
Dep. Variable:            ln_GDP_1985   R-squared:                       0.786
Model:                            OLS   Adj. R-squared:                  0.779
Method:                 Least Squares   F-statistic:                     114.8
Date:                Thu, 29 Oct 2026   Prob (F-statistic):           2.54e-31
Time:                        23:47:33   Log-Likelihood:                -70.576
No. Observations:                  98   AIC:                             149.2
Df Residuals:                      94   BIC:                             159.5
Df Model:                           3
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             6.8444      1.177      5.813      0.000       4.507       9.182
ln_investment     0.6967      0.133      5.245      0.000       0.433       0.960
ln_ngd           -1.7452      0.416     -4.196      0.000      -2.571      -0.919
ln_school         0.6545      0.073      9.001      0.000       0.510       0.799
==============================================================================
Omnibus:                        2.001   Durbin-Watson:                   2.124
Prob(Omnibus):                  0.368   Jarque-Bera (JB):                2.008
Skew:                          -0.330   Prob(JB):                        0.366
Kurtosis:                       2.764   Cond. No.                         115.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:            ln_GDP_1985   R-squared:                       0.784
Model:                            OLS   Adj. R-squared:                  0.779
Method:                 Least Squares   F-statistic:                     172.3
Date:                Thu, 29 Oct 2026   Prob (F-statistic):           2.47e-32
Time:                        23:47:33   Log-Likelihood:                -70.963
No. Observations:                  98   AIC:                             147.9
Df Residuals:                      95   BIC:                             155.7
Df Model:                           2
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            7.8531      0.140     56.082      0.000       7.575       8.131
restricted_k     0.7383      0.124      5.972      0.000       0.493       0.984
restricted_h     0.6571      0.073      9.057      0.000       0.513       0.801
==============================================================================
Omnibus:                        2.571   Durbin-Watson:                   2.047
Prob(Omnibus):                  0.277   Jarque-Bera (JB):                2.582
Skew:                          -0.365   Prob(JB):                        0.275
Kurtosis:                       2.682   Cond. No.                         5.38
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
<F test: F=0.744424878507707, p=0.39044308250096627, df_denom=94, df_num=1>
F-statistic: 0.744424878507707
P-value: 0.39044308250096627
physical capital coefficient: 0.7382848737936389
human capital coefficient: 0.6570786126143494
Implied alpha: 0.3082
Implied beta: 0.2743
se of alpha: 0.0425
se of beta: 0.0332

In [60]:
# Augumented Solow model
# UM of intermediate
intermediate = df[df["Intermediate"] == 1].copy()
y_int_Au = intermediate["ln_GDP_1985"]
X_int_Au = intermediate[["ln_investment", "ln_ngd", "ln_school"]]
X_int_Au = sm.add_constant(X_int_Au)
model_int_Au = sm.OLS(y_int_Au,X_int_Au).fit()
print(model_int_Au.summary())

# RM of intermediated
intermediate["restricted_k"] = (intermediate["ln_investment"] - intermediate["ln_ngd"])
intermediate["restricted_h"] = (intermediate["ln_school"] - intermediate["ln_ngd"])
y_int_Au_r = intermediate["ln_GDP_1985"]
X_int_Au_r = intermediate[["restricted_k", "restricted_h"]]
X_int_Au_r = sm.add_constant(X_int_Au_r)
model_int_Au_r = sm.OLS(y_int_Au_r, X_int_Au_r).fit()
print(model_int_Au_r.summary())

# F test
f_test = model_int_Au.f_test("ln_investment + ln_ngd + ln_school = 0")
print(f_test)
print("F-statistic:", float(f_test.fvalue))
print("P-value:", float(f_test.pvalue))

# alpha and beta
b1 = model_int_Au_r.params["restricted_k"]
b2 = model_int_Au_r.params["restricted_h"]

alpha = b1 / (1+b1+b2)
beta = b2 / (1+b1+b2)

print("physical capital coefficient:", b1)
print("human capital coefficient:", b2)
print("Implied alpha:", round(alpha, 4))
print("Implied beta:", round(beta, 4))

# se of alpha and beta
cov_matrix = model_int_Au_r.cov_params().loc[["restricted_k", "restricted_h"], ["restricted_k", "restricted_h"]].to_numpy()
grad_alpha = np.array([(1 + b2) / (1+b1+b2)**2, -b1 / (1+b1+b2)**2])
grad_beta = np.array([-b2 / (1+b1+b2)**2,(1 + b1) / (1+b1+b2)**2])
se_alpha = np.sqrt(grad_alpha @ cov_matrix @ grad_alpha)
se_beta = np.sqrt(grad_beta @ cov_matrix @ grad_beta)

print("se of alpha:", round(se_alpha, 4))
print("se of beta:", round(se_beta, 4))

                            OLS Regression Results
==============================================================================
Dep. Variable:            ln_GDP_1985   R-squared:                       0.781
Model:                            OLS   Adj. R-squared:                  0.771
Method:                 Least Squares   F-statistic:                     84.25
Date:                Thu, 29 Oct 2026   Prob (F-statistic):           2.44e-23
Time:                        23:58:07   Log-Likelihood:                -45.257
No. Observations:                  75   AIC:                             98.51
Df Residuals:                      71   BIC:                             107.8
Df Model:                           3
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             7.7913      1.192      6.534      0.000       5.414      10.169
ln_investment     0.7004      0.151      4.651      0.000       0.400       1.001
ln_ngd           -1.4998      0.403     -3.720      0.000      -2.304      -0.696
ln_school         0.7305      0.095      7.671      0.000       0.541       0.920
==============================================================================
Omnibus:                        2.500   Durbin-Watson:                   2.352
Prob(Omnibus):                  0.287   Jarque-Bera (JB):                1.944
Skew:                          -0.386   Prob(JB):                        0.378
Kurtosis:                       3.162   Cond. No.                         107.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:            ln_GDP_1985   R-squared:                       0.781
Model:                            OLS   Adj. R-squared:                  0.775
Method:                 Least Squares   F-statistic:                     128.1
Date:                Thu, 29 Oct 2026   Prob (F-statistic):           1.92e-24
Time:                        23:58:07   Log-Likelihood:                -45.268
No. Observations:                  75   AIC:                             96.54
Df Residuals:                      72   BIC:                             103.5
Df Model:                           2
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            7.9662      0.154     51.582      0.000       7.658       8.274
restricted_k     0.7091      0.138      5.151      0.000       0.435       0.983
restricted_h     0.7330      0.093      7.874      0.000       0.547       0.919
==============================================================================
Omnibus:                        2.616   Durbin-Watson:                   2.336
Prob(Omnibus):                  0.270   Jarque-Bera (JB):                2.061
Skew:                          -0.398   Prob(JB):                        0.357
Kurtosis:                       3.156   Cond. No.                         5.82
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
<F test: F=0.021891829696108745, p=0.8827946166760501, df_denom=71, df_num=1>
F-statistic: 0.021891829696108745
P-value: 0.8827946166760501
physical capital coefficient: 0.7090778368472631
human capital coefficient: 0.7330379710795167
Implied alpha: 0.2904
Implied beta: 0.3002
se of alpha: 0.0481
se of beta: 0.04

In [62]:
# Augumented Solow model
# UM of oecd
oecd = df[df["OECD"] == 1].copy()
y_oecd_Au = oecd["ln_GDP_1985"]
X_oecd_Au = oecd[["ln_investment", "ln_ngd", "ln_school"]]
X_oecd_Au = sm.add_constant(X_oecd_Au)
model_oecd_Au = sm.OLS(y_oecd_Au,X_oecd_Au).fit()
print(model_oecd_Au.summary())

# RM of oecd
oecd["restricted_k"] = (oecd["ln_investment"] - oecd["ln_ngd"])
oecd["restricted_h"] = (oecd["ln_school"] - oecd["ln_ngd"])
y_oecd_Au_r = oecd["ln_GDP_1985"]
X_oecd_Au_r = oecd[["restricted_k", "restricted_h"]]
X_oecd_Au_r = sm.add_constant(X_oecd_Au_r)
model_oecd_Au_r = sm.OLS(y_oecd_Au_r, X_oecd_Au_r).fit()
print(model_oecd_Au_r.summary())

# F test
f_test = model_oecd_Au.f_test("ln_investment + ln_ngd + ln_school = 0")
print(f_test)
print("F-statistic:", float(f_test.fvalue))
print("P-value:", float(f_test.pvalue))

# alpha and beta
b1 = model_oecd_Au_r.params["restricted_k"]
b2 = model_oecd_Au_r.params["restricted_h"]

alpha = b1 / (1+b1+b2)
beta = b2 / (1+b1+b2)

print("physical capital coefficient:", b1)
print("human capital coefficient:", b2)
print("Implied alpha:", round(alpha, 4))
print("Implied beta:", round(beta, 4))

# se of alpha and beta
cov_matrix = model_oecd_Au_r.cov_params().loc[["restricted_k", "restricted_h"], ["restricted_k", "restricted_h"]].to_numpy()
grad_alpha = np.array([(1 + b2) / (1+b1+b2)**2, -b1 / (1+b1+b2)**2])
grad_beta = np.array([-b2 / (1+b1+b2)**2,(1 + b1) / (1+b1+b2)**2])
se_alpha = np.sqrt(grad_alpha @ cov_matrix @ grad_alpha)
se_beta = np.sqrt(grad_beta @ cov_matrix @ grad_beta)

print("se of alpha:", round(se_alpha, 4))
print("se of beta:", round(se_beta, 4))

                            OLS Regression Results
==============================================================================
Dep. Variable:            ln_GDP_1985   R-squared:                       0.352
Model:                            OLS   Adj. R-squared:                  0.244
Method:                 Least Squares   F-statistic:                     3.264
Date:                Fri, 30 Oct 2026   Prob (F-statistic):             0.0455
Time:                        00:02:20   Log-Likelihood:                -4.6190
No. Observations:                  22   AIC:                             17.24
Df Residuals:                      18   BIC:                             21.60
Df Model:                           3
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             8.6369      2.214      3.901      0.001       3.985      13.289
ln_investment     0.2761      0.389      0.710      0.487      -0.541       1.093
ln_ngd           -1.0755      0.756     -1.423      0.172      -2.664       0.513
ln_school         0.7676      0.293      2.617      0.017       0.151       1.384
==============================================================================
Omnibus:                        0.378   Durbin-Watson:                   1.832
Prob(Omnibus):                  0.828   Jarque-Bera (JB):                0.167
Skew:                          -0.201   Prob(JB):                        0.920
Kurtosis:                       2.859   Cond. No.                         135.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:            ln_GDP_1985   R-squared:                       0.352
Model:                            OLS   Adj. R-squared:                  0.284
Method:                 Least Squares   F-statistic:                     5.167
Date:                Fri, 30 Oct 2026   Prob (F-statistic):             0.0161
Time:                        00:02:20   Log-Likelihood:                -4.6198
No. Observations:                  22   AIC:                             15.24
Df Residuals:                      19   BIC:                             18.51
Df Model:                           2
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            8.7163      0.466     18.697      0.000       7.741       9.692
restricted_k     0.2829      0.334      0.847      0.407      -0.416       0.982
restricted_h     0.7686      0.284      2.704      0.014       0.174       1.364
==============================================================================
Omnibus:                        0.379   Durbin-Watson:                   1.838
Prob(Omnibus):                  0.827   Jarque-Bera (JB):                0.173
Skew:                          -0.204   Prob(JB):                        0.917
Kurtosis:                       2.853   Cond. No.                         15.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
<F test: F=0.0013507303863485624, p=0.9710870482488055, df_denom=18, df_num=1>
F-statistic: 0.0013507303863485624
P-value: 0.9710870482488055
physical capital coefficient: 0.282870323409536
human capital coefficient: 0.76857131234168
Implied alpha: 0.1379
Implied beta: 0.3746
se of alpha: 0.1472
se of beta: 0.12

In [66]:

# Table I 

table1_models = {"Non-oil": {"Unrestricted": model, "Restricted": model_r}, "Intermediate": {"Unrestricted": model_int, "Restricted": model_int_r}, "OECD": {"Unrestricted": model_oecd, "Restricted": model_oecd_r}}

test_model = table1_models["Non-oil"]["Unrestricted"]

print("Coefficients:")
print(test_model.params)

print("Standard Errors:")
print(test_model.bse)

print("Adjusted R-squared:")
print(test_model.rsquared_adj)

print("Number of observations:")
print(test_model.nobs)

Coefficients:
const            5.429883
ln_investment    1.424014
ln_ngd          -1.989774
dtype: float64
Standard Errors:
const            1.583890
ln_investment    0.143106
ln_ngd           0.563362
dtype: float64
Adjusted R-squared:
0.5924619548106453
Number of observations:
98.0